function dcm = EPtoDCM(ep)
    % quaternion to DCM (rotation matrix)
    dcm = [1 - 2*(ep(2)*ep(2) + ep(3)*ep(3)),...   
           2*(ep(1)*ep(2) + ep(3)*ep(4)),...   
           2*(ep(1)*ep(3) - ep(2)*ep(4)); 
           2*(ep(1)*ep(2) - ep(3)*ep(4)),...
           1 - 2*(ep(1)*ep(1) + ep(3)*ep(3)),...  
           2*(ep(2)*ep(3) + ep(1)*ep(4));
           2*(ep(1)*ep(3) + ep(2)*ep(4)),...   
           2*(ep(2)*ep(3) - ep(1)*ep(4)),...
           1 - 2*(ep(1)*ep(1) + ep(2)*ep(2))];
end